# This workflow can be trigerred manually.

# Don't extend this workflow. If any more steps are needed please extend the
# "publish-release" action in "z_quantum_actions". Allows reusing between repos.
name: publish-release

on:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      # Needed to get access to publish-release action definition
      - name: Check out the released repo
        uses: actions/checkout@v2
        with:
          # Fetch whole repo to get access to tags to read current package
          # version.
          fetch-depth: 0

      # ------------------------------------------------------------------------
      # Loads private SSH key to the SSH agent. Allows to install dependencies 
      # from private git repos, but requires setting `secrets.SSH_PRIVATE_KEY`
      # in repo settings.
      # ------------------------------------------------------------------------
      - uses: ./subtrees/z_quantum_actions/actions/ssh_setup
        with:
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get orquestra-quantum
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-quantum
          path: orquestra-quantum
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get orquestra-opt
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-opt
          path: orquestra-opt
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get orquestra-vqa
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-vqa
          path: orquestra-vqa
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get orquestra-cirq
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-cirq
          path: orquestra-cirq
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get orquestra-qiskit
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-qiskit
          path: orquestra-qiskit
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run publish release action
        uses: ./subtrees/z_quantum_actions/actions/publish-release
